### ISSUE TITLE
Emojis are not inserted

### ISSUE THREAD

**Issue by WhyNotHugo** [hrsh7th/cmp-emoji#1]
I've set up `cmp` with this plugin, but emojis don't get inserted when I pick one.

When I type `:pa`, I get the autocomplete menu just fine. If I press <kbd>tab</kbd> to pick an emoji (e.g.: the panda face), it doesn't insert the emoji, but instead its name (e.g.: `:panda_face:`).

Here's my current config:

```lua
vim.opt.completeopt = { "menu", "menuone", "noselect" }

require("cmp").setup({
  sources = {
    { name = "buffer" },
    { name = "emoji" },
    { name = "nvim_lsp", priority = 100 }, -- Keep LSP results on top.
    { name = "path" },
    { name = "spell" },
    { name = "treesitter" },
    { name = 'nvim_lua' },
  },
  formatting = {
    format = function(entry, vim_item)

      -- set a name for each source
      vim_item.menu = ({
        buffer = "[Buffer]",
        emoji = "[Emoji]",
        nvim_lsp = "[LSP]",
        path = "[Path]",
        spell = "[Spell]",
        treesitter = "[Treesitter]",
        nvim_lua = "[Neovim]",
      })[entry.source.name]
      return vim_item
    end,
  },
})
```

I recently migrated from `nvim-compe`, and this was my previous config. On compe, if I pressed <kbd>tab</kbd> and picked an emoji, it was inserted just fine.

Maybe previously completion was working due to something I've missed porting?

```lua
vim.o.completeopt = "menuone,noselect"

require("compe").setup({
  enabled = true,
  autocomplete = true,
  debug = false,
  min_length = 1,
  preselect = "disable",

  source = {
    path = true,
    buffer = true,
    calc = true,
    vsnip = true,
    nvim_lsp = true,
    nvim_lua = true,
    spell = true,
    tags = true,
    snippets_nvim = true,
    treesitter = true,
    emoji = true,
  },
})
```

**Comment by hrsh7th** [comment]
Implemented.

**Comment by WhyNotHugo** [comment]
Thanks for addressing this!

I've been trying to use:

```lua
require'cmp'.setup {
  sources = {
    { name = 'emoji', insert = true }
  }
}
```

But this still won't insert the emoji -- only the  search text. Am I missing something?

**Comment by pbakiewicz** [comment]
Why this issue is closed? I'm getting the same result as OP three years later. Just vanilla config and only emoji text is inserted not the actual emoij.

**Comment by WhyNotHugo** [comment]
I really don't see what the use case could be for inserting the _name_ of an emoji instead of the emoji itself, but `cmp-emoji` doesn't actually insert emoji by default, it inserts the name instead (see: https://github.com/hrsh7th/nvim-cmp/issues/250#issuecomment-928102924). 

You can enable insertion of emojis with:

```
require("cmp").setup({
  sources = {
    { name = "emoji", option = { insert = true } },
...
```
